completed footer ui
anasbinarif/ace-my-exam pull request #11
Opened 2024-10-14 15:58 UTC by MEH-NAZZ

![image](https://github.com/user-attachments/assets/7d13bff7-4088-4cc0-80b1-be8a1a84a22b)

2024-10-14 20:43 UTC, anasbinarif requested changes

2024-10-14 20:43 UTC, anasbinarif commented on src/features/footer/Footer.tsx
> +import {ListItem } from '@mui/material';
i would say you have made this component complex just by having style in a separate file, like even if you want to have styles in a separate file use classes or style, in this way I have to style the file to see what doing on in the component, like Link, List, these should be in the components

2024-10-16 15:34 UTC, fizo-neechan approved these changes

2024-10-16 22:58 UTC, anasbinarif approved these changes

2024-10-17 12:23 UTC, merged